OPTIONS (SKIP=1)
LOAD DATA
INFILE 'FileData/continentes.csv'
INTO TABLE CONTINENTES TRUNCATE
FIELDS TERMINATED BY "," TRAILING NULLCOLS
(
CONTINENTE "TRIM(:CONTINENTE)",
NACION "TRIM(:NACION)",
CAPITAL "TRIM(:CAPITAL)",
REGION "TRIM(:REGION)"
)
