OPTIONS (SKIP=1)
LOAD DATA
INFILE 'FileData/patentes.csv'
INTO TABLE PATENTES TRUNCATE
FIELDS TERMINATED BY "$" TRAILING NULLCOLS
(
CODIGOPATENTE "TRIM(:CODIGOPATENTE)",
ANIOPUBLI "TRIM(:ANIOPUBLI)",
DESCRIPPATENTE "TRIM(:DESCRIPPATENTE)",
PAIS "TRIM(:PAIS)",
RANKINGAREA "TRIM(:RANKINGAREA)",
AREAINVESTIGACION "TRIM(:AREAINVESTIGACION)",
DESCRIPAREA "TRIM(:DESCRIPAREA)",
INVENTOR "TRIM(:INVENTOR)",
NACIONALIDAD "TRIM(:NACIONALIDAD)"
)
