/** consulta 1
PORCENTAJE DE INVENTORES PAIS*/
SELECT ID_REGION ,
NOMBRE ,
TRUNC(PORCENTAJE,7) AS PORCENTAJE  FROM(
SELECT P.ID_REGION, P.NOMBRE, COUNT(*)/ P.POBLACION AS PORCENTAJE
FROM(
SELECT R.ID_REGION, R.NOMBRE, R.POBLACION
FROM REGION R
WHERE R.TIPO = 'N') P, INVENTOR I
WHERE P.ID_REGION = I.ID_REGION
GROUP BY P.ID_REGION, P.NOMBRE, P.POBLACION) A
ORDER BY A.PORCENTAJE DESC;

/**
*CONSULTA 2
*/
SELECT R.ID_REGION, R.NOMBRE
FROM REGION R
WHERE R.ID_REGION  NOT IN (
  SELECT R.ID_REGION
  FROM INVENTOR I , REGION R
  WHERE I.ID_REGION = R.ID_REGION
  GROUP BY R.ID_REGION
  UNION
  SELECT S.ID_REGION
  FROM INVENTO INV , REGION S
  WHERE INV.ID_REGION = S.ID_REGION
  GROUP BY S.ID_REGION
) AND R.TIPO = 'N';

/**
*CONSULTA 3
**/
SELECT
S.ID_REGION,S.NOMBRE,S.AREA, INV.INVS, TRUNC(INV.INVS/S.AREA,8) AS "INV/AREA"
FROM(
SELECT R1.ID_REGION, SUM( R2.AREA) AS AREA , R1.NOMBRE
FROM REGION R1, REGION R2 
WHERE R1.TIPO = 'R' AND R2.ID_REGION1 = R1.ID_REGION
GROUP BY R1.ID_REGION, R1.NOMBRE) S,
(SELECT R.ID_REGION1, COUNT(*) AS INVS
FROM INVENTO I, REGION R
WHERE I.ID_REGION = R.ID_REGION
GROUP BY R.ID_REGION1) INV
WHERE S.ID_REGION = INV.ID_REGION1
ORDER BY "INV/AREA" DESC;

/**
*consulta 4
*/

SELECT I.ID_AREA,A.NOMBRE, COUNT(*) AS INVENTOS 
FROM INVENTO I, AREA A
WHERE A.ID_AREA = I.ID_AREA AND I.ESTADO = 'P'
GROUP BY I.ID_AREA, A.NOMBRE
ORDER BY INVENTOS DESC;

/**
*CONSULTA 5
*/

SELECT
R.ID_AREA, A.NOMBRE,
SUM( CASE WHEN R.INVENTORES > 1 THEN 1 ELSE 0 END ) AS INV 
FROM
(SELECT COUNT(*) AS INVENTORES,
DI.ID_INVENTO, V.ID_AREA
FROM DET_INVENTO DI, INVENTO V
WHERE DI.ID_INVENTO = V.ID_INVENTO  AND V.ESTADO = 'P'
GROUP BY DI.ID_INVENTO, V.ID_AREA) R , AREA A
WHERE R.ID_AREA = A.ID_AREA
GROUP BY R.ID_AREA,A.NOMBRE;


/****
CONSULTA 6 FALTA
*/


/**
CONSULTA 7
*/
SELECT A.TIN AS TODOS, B.NIN AS NNA, TRUNC( B.NIN/A.TIN, 6) AS PROB 
FROM(
SELECT COUNT(*) AS TIN
FROM
(
  SELECT R.ID_REGION
  FROM
  (
    SELECT R2.ID_REGION FROM
    REGION R1, REGION R2
    WHERE R1.NOMBRE ='América' AND R2.ID_REGION1 = R1.ID_REGION) L, REGION R
  WHERE R.ID_REGION1 IN L.ID_REGION) C, INVENTOR I
WHERE C.ID_REGION = I.ID_REGION
) A,(
SELECT COUNT(*) AS NIN
FROM(
  SELECT R.ID_REGION
  FROM
  (
    SELECT R2.ID_REGION FROM
    REGION R1, REGION R2
    WHERE R1.NOMBRE ='América' AND R2.ID_REGION1 = R1.ID_REGION AND R2.NOMBRE <> 'América del norte'
  ) L, REGION R
  WHERE R.ID_REGION1 IN L.ID_REGION
) C, INVENTOR I
WHERE I.ID_REGION IN C.ID_REGION) B;

/**
CONSULTA 8 
FALTA
**/


/**CONSULTA 9
ESTA AUN NO ESTA CORRECTAMENTE HECHA
**/
SELECT T.NOMBRE, T.FECHA_INI, T.SALARIO
FROM TRABAJADOR T
ORDER BY T.SALARIO DESC , T.FECHA_INI ASC;

/**
*CONSULTA 10
**/
SELECT COUNT(*)
FROM INVENTO WHERE ESTADO = 'P';

SELECT P.ID_INVENTO, COUNT(*) AS REGIONES
FROM
(
SELECT I.ID_INVENTO, I.ID_REGION
FROM INVENTO I
WHERE I.ESTADO = 'P') P,
FRONTERA F
WHERE P.ID_REGION = F.ID_REGION
GROUP BY P.ID_INVENTO
ORDER BY REGIONES DESC;
